package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum CONTENTS implements MetaVar {
CONTENTS_AREAPORTAL("CONTENTS_AREAPORTAL"),
CONTENTS_AUX("CONTENTS_AUX"),
CONTENTS_BLOCKLOS("CONTENTS_BLOCKLOS"),
CONTENTS_CURRENT_0("CONTENTS_CURRENT_0"),
CONTENTS_CURRENT_180("CONTENTS_CURRENT_180"),
CONTENTS_CURRENT_270("CONTENTS_CURRENT_270"),
CONTENTS_CURRENT_90("CONTENTS_CURRENT_90"),
CONTENTS_CURRENT_DOWN("CONTENTS_CURRENT_DOWN"),
CONTENTS_CURRENT_UP("CONTENTS_CURRENT_UP"),
CONTENTS_DEBRIS("CONTENTS_DEBRIS"),
CONTENTS_DETAIL("CONTENTS_DETAIL"),
CONTENTS_EMPTY("CONTENTS_EMPTY"),
CONTENTS_GRATE("CONTENTS_GRATE"),
CONTENTS_HITBOX("CONTENTS_HITBOX"),
CONTENTS_IGNORE_NODRAW_OPAQUE("CONTENTS_IGNORE_NODRAW_OPAQUE"),
CONTENTS_LADDER("CONTENTS_LADDER"),
CONTENTS_MONSTER("CONTENTS_MONSTER"),
CONTENTS_MONSTERCLIP("CONTENTS_MONSTERCLIP"),
CONTENTS_MOVEABLE("CONTENTS_MOVEABLE"),
CONTENTS_OPAQUE("CONTENTS_OPAQUE"),
CONTENTS_ORIGIN("CONTENTS_ORIGIN"),
CONTENTS_PLAYERCLIP("CONTENTS_PLAYERCLIP"),
CONTENTS_SLIME("CONTENTS_SLIME"),
CONTENTS_SOLID("CONTENTS_SOLID"),
CONTENTS_TEAM1("CONTENTS_TEAM1"),
CONTENTS_TEAM2("CONTENTS_TEAM2"),
CONTENTS_TEAM3("CONTENTS_TEAM3"),
CONTENTS_TEAM4("CONTENTS_TEAM4"),
CONTENTS_TESTFOGVOLUME("CONTENTS_TESTFOGVOLUME"),
CONTENTS_TRANSLUCENT("CONTENTS_TRANSLUCENT"),
CONTENTS_WATER("CONTENTS_WATER"),
CONTENTS_WINDOW("CONTENTS_WINDOW"),
;
	private String name;
	private CONTENTS(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
