package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum DMG implements MetaVar {
DMG_ACID("DMG_ACID"),
DMG_AIRBOAT("DMG_AIRBOAT"),
DMG_ALWAYSGIB("DMG_ALWAYSGIB"),
DMG_BLAST("DMG_BLAST"),
DMG_BLAST_SURFACE("DMG_BLAST_SURFACE"),
DMG_BUCKSHOT("DMG_BUCKSHOT"),
DMG_BULLET("DMG_BULLET"),
DMG_BURN("DMG_BURN"),
DMG_CLUB("DMG_CLUB"),
DMG_CRUSH("DMG_CRUSH"),
DMG_DIRECT("DMG_DIRECT"),
DMG_DISSOLVE("DMG_DISSOLVE"),
DMG_DROWN("DMG_DROWN"),
DMG_DROWNRECOVER("DMG_DROWNRECOVER"),
DMG_ENERGYBEAM("DMG_ENERGYBEAM"),
DMG_FALL("DMG_FALL"),
DMG_GENERIC("DMG_GENERIC"),
DMG_NERVEGAS("DMG_NERVEGAS"),
DMG_NEVERGIB("DMG_NEVERGIB"),
DMG_PARALYZE("DMG_PARALYZE"),
DMG_PHYSGUN("DMG_PHYSGUN"),
DMG_PLASMA("DMG_PLASMA"),
DMG_POISON("DMG_POISON"),
DMG_PREVENT_PHYSICS_FORCE("DMG_PREVENT_PHYSICS_FORCE"),
DMG_RADIATION("DMG_RADIATION"),
DMG_REMOVENORAGDOLL("DMG_REMOVENORAGDOLL"),
DMG_SHOCK("DMG_SHOCK"),
DMG_SLASH("DMG_SLASH"),
DMG_SLOWBURN("DMG_SLOWBURN"),
DMG_SONIC("DMG_SONIC"),
DMG_VEHICLE("DMG_VEHICLE"),
;
	private String name;
	private DMG(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
