package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum FCVAR implements MetaVar {
FCVAR_ARCHIVE("FCVAR_ARCHIVE"),
FCVAR_ARCHIVE_XBOX("FCVAR_ARCHIVE_XBOX"),
FCVAR_CHEAT("FCVAR_CHEAT"),
FCVAR_CLIENTCMD_CAN_EXECUTE("FCVAR_CLIENTCMD_CAN_EXECUTE"),
FCVAR_CLIENTDLL("FCVAR_CLIENTDLL"),
FCVAR_DEMO("FCVAR_DEMO"),
FCVAR_DONTRECORD("FCVAR_DONTRECORD"),
FCVAR_GAMEDLL("FCVAR_GAMEDLL"),
FCVAR_NEVER_AS_STRING("FCVAR_NEVER_AS_STRING"),
FCVAR_NONE("FCVAR_NONE"),
FCVAR_NOTIFY("FCVAR_NOTIFY"),
FCVAR_NOT_CONNECTED("FCVAR_NOT_CONNECTED"),
FCVAR_PRINTABLEONLY("FCVAR_PRINTABLEONLY"),
FCVAR_PROTECTED("FCVAR_PROTECTED"),
FCVAR_REPLICATED("FCVAR_REPLICATED"),
FCVAR_SERVER_CANNOT_QUERY("FCVAR_SERVER_CANNOT_QUERY"),
FCVAR_SERVER_CAN_EXECUTE("FCVAR_SERVER_CAN_EXECUTE"),
FCVAR_SPONLY("FCVAR_SPONLY"),
FCVAR_UNLOGGED("FCVAR_UNLOGGED"),
FCVAR_UNREGISTERED("FCVAR_UNREGISTERED"),
FCVAR_USERINFO("FCVAR_USERINFO"),
;
	private String name;
	private FCVAR(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
