package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum MASK implements MetaVar {
MASK_ALL("MASK_ALL"),
MASK_BLOCKLOS("MASK_BLOCKLOS"),
MASK_BLOCKLOS_AND_NPCS("MASK_BLOCKLOS_AND_NPCS"),
MASK_CURRENT("MASK_CURRENT"),
MASK_DEADSOLID("MASK_DEADSOLID"),
MASK_NPCSOLID("MASK_NPCSOLID"),
MASK_NPCSOLID_BRUSHONLY("MASK_NPCSOLID_BRUSHONLY"),
MASK_NPCWORLDSTATIC("MASK_NPCWORLDSTATIC"),
MASK_OPAQUE("MASK_OPAQUE"),
MASK_OPAQUE_AND_NPCS("MASK_OPAQUE_AND_NPCS"),
MASK_PLAYERSOLID("MASK_PLAYERSOLID"),
MASK_PLAYERSOLID_BRUSHONLY("MASK_PLAYERSOLID_BRUSHONLY"),
MASK_SHOT("MASK_SHOT"),
MASK_SHOT_HULL("MASK_SHOT_HULL"),
MASK_SHOT_PORTAL("MASK_SHOT_PORTAL"),
MASK_SOLID("MASK_SOLID"),
MASK_SOLID_BRUSHONLY("MASK_SOLID_BRUSHONLY"),
MASK_SPLITAREAPORTAL("MASK_SPLITAREAPORTAL"),
MASK_VISIBLE("MASK_VISIBLE"),
MASK_VISIBLE_AND_NPCS("MASK_VISIBLE_AND_NPCS"),
MASK_WATER("MASK_WATER"),
;
	private String name;
	private MASK(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
