package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum PLAYERANIMEVENT implements MetaVar {
PLAYERANIMEVENT_ATTACK_GRENADE("PLAYERANIMEVENT_ATTACK_GRENADE"),
PLAYERANIMEVENT_ATTACK_PRIMARY("PLAYERANIMEVENT_ATTACK_PRIMARY"),
PLAYERANIMEVENT_ATTACK_SECONDARY("PLAYERANIMEVENT_ATTACK_SECONDARY"),
PLAYERANIMEVENT_CANCEL("PLAYERANIMEVENT_CANCEL"),
PLAYERANIMEVENT_CUSTOM("PLAYERANIMEVENT_CUSTOM"),
PLAYERANIMEVENT_CUSTOM_GESTURE("PLAYERANIMEVENT_CUSTOM_GESTURE"),
PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE("PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE"),
PLAYERANIMEVENT_CUSTOM_SEQUENCE("PLAYERANIMEVENT_CUSTOM_SEQUENCE"),
PLAYERANIMEVENT_DIE("PLAYERANIMEVENT_DIE"),
PLAYERANIMEVENT_DOUBLEJUMP("PLAYERANIMEVENT_DOUBLEJUMP"),
PLAYERANIMEVENT_FLINCH_CHEST("PLAYERANIMEVENT_FLINCH_CHEST"),
PLAYERANIMEVENT_FLINCH_HEAD("PLAYERANIMEVENT_FLINCH_HEAD"),
PLAYERANIMEVENT_FLINCH_LEFTARM("PLAYERANIMEVENT_FLINCH_LEFTARM"),
PLAYERANIMEVENT_FLINCH_LEFTLEG("PLAYERANIMEVENT_FLINCH_LEFTLEG"),
PLAYERANIMEVENT_FLINCH_RIGHTARM("PLAYERANIMEVENT_FLINCH_RIGHTARM"),
PLAYERANIMEVENT_FLINCH_RIGHTLEG("PLAYERANIMEVENT_FLINCH_RIGHTLEG"),
PLAYERANIMEVENT_JUMP("PLAYERANIMEVENT_JUMP"),
PLAYERANIMEVENT_RELOAD("PLAYERANIMEVENT_RELOAD"),
PLAYERANIMEVENT_RELOAD_END("PLAYERANIMEVENT_RELOAD_END"),
PLAYERANIMEVENT_RELOAD_LOOP("PLAYERANIMEVENT_RELOAD_LOOP"),
PLAYERANIMEVENT_SNAP_YAW("PLAYERANIMEVENT_SNAP_YAW"),
PLAYERANIMEVENT_SPAWN("PLAYERANIMEVENT_SPAWN"),
PLAYERANIMEVENT_SWIM("PLAYERANIMEVENT_SWIM"),
;
	private String name;
	private PLAYERANIMEVENT(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
