package com.crazyt.gmod.enums;
import com.crazyt.mcf.MetaVar;
public enum RENDERMODE implements MetaVar {
RENDERMODE_ENVIROMENTAL("RENDERMODE_ENVIROMENTAL"),
RENDERMODE_GLOW("RENDERMODE_GLOW"),
RENDERMODE_NONE("RENDERMODE_NONE"),
RENDERMODE_NORMAL("RENDERMODE_NORMAL"),
RENDERMODE_TRANSADD("RENDERMODE_TRANSADD"),
RENDERMODE_TRANSADDFRAMEBLEND("RENDERMODE_TRANSADDFRAMEBLEND"),
RENDERMODE_TRANSALPHA("RENDERMODE_TRANSALPHA"),
RENDERMODE_TRANSALPHADD("RENDERMODE_TRANSALPHADD"),
RENDERMODE_TRANSCOLOR("RENDERMODE_TRANSCOLOR"),
RENDERMODE_TRANSTEXTURE("RENDERMODE_TRANSTEXTURE"),
RENDERMODE_WORLDGLOW("RENDERMODE_WORLDGLOW"),
;
	private String name;
	private RENDERMODE(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
