package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum BONE implements MetaVar {
BONE_ALWAYS_PROCEDURAL("BONE_ALWAYS_PROCEDURAL"),
BONE_CALCULATE_MASK("BONE_CALCULATE_MASK"),
BONE_PHYSICALLY_SIMULATED("BONE_PHYSICALLY_SIMULATED"),
BONE_PHYSICS_PROCEDURAL("BONE_PHYSICS_PROCEDURAL"),
BONE_SCREEN_ALIGN_CYLINDER("BONE_SCREEN_ALIGN_CYLINDER"),
BONE_SCREEN_ALIGN_SPHERE("BONE_SCREEN_ALIGN_SPHERE"),
BONE_USED_BY_ANYTHING("BONE_USED_BY_ANYTHING"),
BONE_USED_BY_ATTACHMENT("BONE_USED_BY_ATTACHMENT"),
BONE_USED_BY_BONE_MERGE("BONE_USED_BY_BONE_MERGE"),
BONE_USED_BY_HITBOX("BONE_USED_BY_HITBOX"),
BONE_USED_BY_VERTEX_LOD0("BONE_USED_BY_VERTEX_LOD0"),
BONE_USED_BY_VERTEX_LOD1("BONE_USED_BY_VERTEX_LOD1"),
BONE_USED_BY_VERTEX_LOD2("BONE_USED_BY_VERTEX_LOD2"),
BONE_USED_BY_VERTEX_LOD3("BONE_USED_BY_VERTEX_LOD3"),
BONE_USED_BY_VERTEX_LOD4("BONE_USED_BY_VERTEX_LOD4"),
BONE_USED_BY_VERTEX_LOD5("BONE_USED_BY_VERTEX_LOD5"),
BONE_USED_BY_VERTEX_LOD6("BONE_USED_BY_VERTEX_LOD6"),
BONE_USED_BY_VERTEX_LOD7("BONE_USED_BY_VERTEX_LOD7"),
BONE_USED_BY_VERTEX_MASK("BONE_USED_BY_VERTEX_MASK"),
BONE_USED_MASK("BONE_USED_MASK"),
;
	private String name;
	private BONE(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
