package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum COLLISION implements MetaVar {
COLLISION_GROUP_BREAKABLE_GLASS("COLLISION_GROUP_BREAKABLE_GLASS"),
COLLISION_GROUP_DEBRIS("COLLISION_GROUP_DEBRIS"),
COLLISION_GROUP_DEBRIS_TRIGGER("COLLISION_GROUP_DEBRIS_TRIGGER"),
COLLISION_GROUP_DISSOLVING("COLLISION_GROUP_DISSOLVING"),
COLLISION_GROUP_DOOR_BLOCKER("COLLISION_GROUP_DOOR_BLOCKER"),
COLLISION_GROUP_INTERACTIVE("COLLISION_GROUP_INTERACTIVE"),
COLLISION_GROUP_INTERACTIVE_DEBRIS("COLLISION_GROUP_INTERACTIVE_DEBRIS"),
COLLISION_GROUP_IN_VEHICLE("COLLISION_GROUP_IN_VEHICLE"),
COLLISION_GROUP_NONE("COLLISION_GROUP_NONE"),
COLLISION_GROUP_NPC("COLLISION_GROUP_NPC"),
COLLISION_GROUP_NPC_ACTOR("COLLISION_GROUP_NPC_ACTOR"),
COLLISION_GROUP_NPC_SCRIPTED("COLLISION_GROUP_NPC_SCRIPTED"),
COLLISION_GROUP_PASSABLE_DOOR("COLLISION_GROUP_PASSABLE_DOOR"),
COLLISION_GROUP_PLAYER("COLLISION_GROUP_PLAYER"),
COLLISION_GROUP_PLAYER_MOVEMENT("COLLISION_GROUP_PLAYER_MOVEMENT"),
COLLISION_GROUP_PROJECTILE("COLLISION_GROUP_PROJECTILE"),
COLLISION_GROUP_PUSHAWAY("COLLISION_GROUP_PUSHAWAY"),
COLLISION_GROUP_VEHICLE("COLLISION_GROUP_VEHICLE"),
COLLISION_GROUP_VEHICLE_CLIP("COLLISION_GROUP_VEHICLE_CLIP"),
COLLISION_GROUP_WEAPON("COLLISION_GROUP_WEAPON"),
COLLISION_GROUP_WORLD("COLLISION_GROUP_WORLD"),
;
	private String name;
	private COLLISION(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
