package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum FVPHYSICS implements MetaVar {
FVPHYSICS_CONSTRAINT_STATIC("FVPHYSICS_CONSTRAINT_STATIC"),
FVPHYSICS_DMG_DISSOLVE("FVPHYSICS_DMG_DISSOLVE"),
FVPHYSICS_DMG_SLICE("FVPHYSICS_DMG_SLICE"),
FVPHYSICS_HEAVY_OBJECT("FVPHYSICS_HEAVY_OBJECT"),
FVPHYSICS_MULTIOBJECT_ENTITY("FVPHYSICS_MULTIOBJECT_ENTITY"),
FVPHYSICS_NO_IMPACT_DMG("FVPHYSICS_NO_IMPACT_DMG"),
FVPHYSICS_NO_NPC_IMPACT_DMG("FVPHYSICS_NO_NPC_IMPACT_DMG"),
FVPHYSICS_NO_PLAYER_PICKUP("FVPHYSICS_NO_PLAYER_PICKUP"),
FVPHYSICS_NO_SELF_COLLISIONS("FVPHYSICS_NO_SELF_COLLISIONS"),
FVPHYSICS_PART_OF_RAGDOLL("FVPHYSICS_PART_OF_RAGDOLL"),
FVPHYSICS_PENETRATING("FVPHYSICS_PENETRATING"),
FVPHYSICS_PLAYER_HELD("FVPHYSICS_PLAYER_HELD"),
FVPHYSICS_WAS_THROWN("FVPHYSICS_WAS_THROWN"),
;
	private String name;
	private FVPHYSICS(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
