package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum STENCILOPERATION implements MetaVar {
STENCILOPERATION_DECR("STENCILOPERATION_DECR"),
STENCILOPERATION_DECRSAT("STENCILOPERATION_DECRSAT"),
STENCILOPERATION_INCR("STENCILOPERATION_INCR"),
STENCILOPERATION_INCRSAT("STENCILOPERATION_INCRSAT"),
STENCILOPERATION_INVERT("STENCILOPERATION_INVERT"),
STENCILOPERATION_KEEP("STENCILOPERATION_KEEP"),
STENCILOPERATION_REPLACE("STENCILOPERATION_REPLACE"),
STENCILOPERATION_ZERO("STENCILOPERATION_ZERO"),
;
	private String name;
	private STENCILOPERATION(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
