package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum STENCIL implements MetaVar {
STENCIL_ALWAYS("STENCIL_ALWAYS"),
STENCIL_DECR("STENCIL_DECR"),
STENCIL_DECRSAT("STENCIL_DECRSAT"),
STENCIL_EQUAL("STENCIL_EQUAL"),
STENCIL_GREATER("STENCIL_GREATER"),
STENCIL_GREATEREQUAL("STENCIL_GREATEREQUAL"),
STENCIL_INCR("STENCIL_INCR"),
STENCIL_INCRSAT("STENCIL_INCRSAT"),
STENCIL_INVERT("STENCIL_INVERT"),
STENCIL_KEEP("STENCIL_KEEP"),
STENCIL_LESS("STENCIL_LESS"),
STENCIL_LESSEQUAL("STENCIL_LESSEQUAL"),
STENCIL_NEVER("STENCIL_NEVER"),
STENCIL_NOTEQUAL("STENCIL_NOTEQUAL"),
STENCIL_REPLACE("STENCIL_REPLACE"),
STENCIL_ZERO("STENCIL_ZERO"),
;
	private String name;
	private STENCIL(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
