package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum STENCILCOMPARISONFUNCTION implements MetaVar {
STENCILCOMPARISONFUNCTION_ALWAYS("STENCILCOMPARISONFUNCTION_ALWAYS"),
STENCILCOMPARISONFUNCTION_EQUAL("STENCILCOMPARISONFUNCTION_EQUAL"),
STENCILCOMPARISONFUNCTION_GREATER("STENCILCOMPARISONFUNCTION_GREATER"),
STENCILCOMPARISONFUNCTION_GREATEREQUAL("STENCILCOMPARISONFUNCTION_GREATEREQUAL"),
STENCILCOMPARISONFUNCTION_LESS("STENCILCOMPARISONFUNCTION_LESS"),
STENCILCOMPARISONFUNCTION_LESSEQUAL("STENCILCOMPARISONFUNCTION_LESSEQUAL"),
STENCILCOMPARISONFUNCTION_NEVER("STENCILCOMPARISONFUNCTION_NEVER"),
STENCILCOMPARISONFUNCTION_NOTEQUAL("STENCILCOMPARISONFUNCTION_NOTEQUAL"),
;
	private String name;
	private STENCILCOMPARISONFUNCTION(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
