package com.crazyt.gmod;
import com.crazyt.mcf.MetaVar;
public enum TYPE implements MetaVar {
TYPE_AISCHEDULE("TYPE_AISCHEDULE"),
TYPE_ANGLE("TYPE_ANGLE"),
TYPE_BOOL("TYPE_BOOL"),
TYPE_CONVAR("TYPE_CONVAR"),
TYPE_COUNT("TYPE_COUNT"),
TYPE_DAMAGEINFO("TYPE_DAMAGEINFO"),
TYPE_DLIGHT("TYPE_DLIGHT"),
TYPE_EFFECTDATA("TYPE_EFFECTDATA"),
TYPE_ENTITY("TYPE_ENTITY"),
TYPE_FILE("TYPE_FILE"),
TYPE_FUNCTION("TYPE_FUNCTION"),
TYPE_HTTPGET("TYPE_HTTPGET"),
TYPE_IMESH("TYPE_IMESH"),
TYPE_INVALID("TYPE_INVALID"),
TYPE_LIGHTUSERDATA("TYPE_LIGHTUSERDATA"),
TYPE_MATERIAL("TYPE_MATERIAL"),
TYPE_MATRIX("TYPE_MATRIX"),
TYPE_MOVEDATA("TYPE_MOVEDATA"),
TYPE_NIL("TYPE_NIL"),
TYPE_NUMBER("TYPE_NUMBER"),
TYPE_PANEL("TYPE_PANEL"),
TYPE_PARTICLE("TYPE_PARTICLE"),
TYPE_PARTICLEEMITTER("TYPE_PARTICLEEMITTER"),
TYPE_PHYSOBJ("TYPE_PHYSOBJ"),
TYPE_PIXELVISHANDLE("TYPE_PIXELVISHANDLE"),
TYPE_RECIPIENTFILTER("TYPE_RECIPIENTFILTER"),
TYPE_RESTORE("TYPE_RESTORE"),
TYPE_SAVE("TYPE_SAVE"),
TYPE_SCRIPTEDVEHICLE("TYPE_SCRIPTEDVEHICLE"),
TYPE_SOUND("TYPE_SOUND"),
TYPE_STRING("TYPE_STRING"),
TYPE_TABLE("TYPE_TABLE"),
TYPE_TEXTURE("TYPE_TEXTURE"),
TYPE_THREAD("TYPE_THREAD"),
TYPE_USERCMD("TYPE_USERCMD"),
TYPE_USERMSG("TYPE_USERMSG"),
TYPE_VECTOR("TYPE_VECTOR"),
TYPE_VIDEO("TYPE_VIDEO"),
;
	private String name;
	private TYPE(String name){
		this.name = name;
	}
	@Override
	public String _getName() {
		return name;
	}
	@Override
	public void _setName(String name) {}
}
